# travis-ci.org configuration
# 
language: generic
sudo: required
dist: trusty
env:
    global:
        - secure: "CoI8hwHH1yfQoQxIfWGRS0WfTyScox+5aJn0fDDgz2uKrrIxmBvIw/WKX8wcSiV6fLmLuwgNkKqSM3hdO4qaG+JxfWcuEiZZHm+kxSGMkWbGb/fvAI+gHg8ldKyYttcIX71O5rlZiC2QpNKQi2v18S6pI5p8eqnx7DYx4YrmguQ="
       # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
       #   via the "travis encrypt" command using the project repo's public key
        - secure: "C9ZJ9LYnuowRdF4D66KLfquimvu8GtRGIafwvCcGYKReEy8phlBdFsHlybkMBNYJNTJSM0j6wyo1lKTVGHxmpQDimjR7kmxUtawbhuJ5qOCBtFqNVh9lRQi7hC4+UOhvRsIcbV8HAJM5u/5RxGOfXCePK3a2DtiYv1d2NHToZN8="
compiler:
    - gcc
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install libcap2-bin
    #- sudo apt-get install traceroute
    #- traceroute google.com
    - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
install:
    - ci/build-1-autotools.sh
    - curl -L http://cpanmin.us | perl - --sudo App::cpanminus
    - cpanm --sudo Test::Command
script:
    - ci/build-2-install.sh
    - env PATH=`pwd`/src:$PATH prove ci/test-*.pl
    - ci/test-tarball.sh
after_success:
    - ci/coveralls.sh
    - ci/deploy-bintray.sh

addons:
  coverity_scan:
    project:
      name: "schweikert/fping"
      description: "Build submitted via Travis CI"
    notification_email: david@schweikert.ch
    #build_command_prepend: "ci/build-2-install.sh"
    build_command:   "ci/build-2-install.sh"
    branch_pattern: coverity_scan
